### ISSUE TITLE
Add conditional operator

### ISSUE THREAD

**Issue by pacbard** [wmvanvliet/Kerbulator#26]
Sometimes, it is helpful to have a conditional operator (especially when working with angles).

I looked at the JIT compiler and it does not support ternary operators. The standard C# operator (```?:```) might also not work because ```:``` is already used for in/out statements.

Probably, the best way to address the issue is to create a build in function ```if``` similar to MySQL IF or fortran's merge.

Also, I don't think that Kerbulator has comparison operators, so they need to be added as well.

**Comment by wmvanvliet** [comment]
I've been thinking about this and welcome your opinion on this matter.

What I do **not** want to do is write a programming language. There's no point. You can already program KSP in C#, KSPTOT provides an interface to MATLAB, kOS is an in-game programming language.

What I **do** want to do is provide a way for the user to quickly apply mathematical equations. Going from a formula on a piece of paper in front of you to a working version in Kerbulator should be as easy as possible. So I would like to keep the language as small, yet functional, as possible.

That leads us to the conditional operator. At the beginning, I rejected it, because it would lead to the implementation of comparison operators and quickly explode the language into a poor mans programming language. But I've come across situations where it would be very useful (for example dealing with wrapping angles around 0º and 180º) to have an `if` statement.

If we implement this, I would like it to mimic the mathematical notation:
![conditional](https://cloud.githubusercontent.com/assets/428273/7677064/5981c37a-fd49-11e4-8b6f-836637a51ebd.png)

rather than mimic a programming language.

**Comment by wmvanvliet** [comment]
I would like to write:

    x = (x^2-x) / x, if x ≥ 1
                  0, otherwise

**Comment by pacbard** [comment]
I really like your idea. It is simple and it will be easier to move calculations from paper to Kerbulator. It will also be more user friendly than something like:

    x = (x^2-x) / x ? x ≥ 1 : 0

I also agree with not wanting to implement a half baked language. We already have enough options if you want to program with KSP (e.g., kOS, kRPC, KSPTOT).

Now I am thinking on how to implement it with the current code base. There are two possible ways to do it:
 - Add a new operator (```=?``` could make sense) that handles an assignment with an if-then cycle
 - Add a build-in function (maybe ```piecewise()```, a-la mathematica) that handles the assignment with a return. In this case, the function must handle an unknown number of parameters (probably using the ```params object[] list``` trick)

Either way, it will be easier to handle conditional assignments

**Comment by wmvanvliet** [comment]
I've finished the implementation of this construct. Take a look at the [unit tests](https://github.com/wmvanvliet/Kerbulator/blob/master/tests/piecewise.math) and at the [language reference](https://github.com/wmvanvliet/Kerbulator/blob/master/doc/langref.mkd#piecewise-functions-aka-if-statements-or-branching-statements) to see how it works!
